### ISSUE TITLE
Error on first install

### ISSUE THREAD

**Issue by andrei1058** [andrei1058/SteveSus#18]
I am getting this error on server load using a wip build for #16 

sv: spigot 1.20

```
[00:26:26] [Server thread/INFO]: Starting minecraft server version 1.12.2
[00:26:26] [Server thread/INFO]: Loading properties
[00:26:26] [Server thread/INFO]: Default game type: SURVIVAL
[00:26:26] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-642f6d2-57ab4cf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[00:26:26] [Server thread/INFO]: Debug logging is disabled
[00:26:26] [Server thread/INFO]: Server Ping Player Sample Count: 12

[00:26:26] [Server thread/INFO]: Using 4 threads for Netty based IO
[00:26:26] [Server thread/INFO]: Generating keypair
[00:26:26] [Server thread/INFO]: Starting Minecraft server on *:25565
[00:26:26] [Server thread/INFO]: Using epoll channel type
[00:26:26] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[00:26:26] [Server thread/INFO]: [SteveSus] Loading SteveSus v1.4.3-beta
[00:26:26] [Server thread/ERROR]: 'void org.yaml.snakeyaml.nodes.ScalarNode.<init>(org.yaml.snakeyaml.nodes.Tag, java.lang.String, org.yaml.snakeyaml.error.Mark, org.yaml.snakeyaml.error.Mark, org.yaml.snakeyaml.DumperOptions$ScalarStyle)' initializing SteveSus v1.4.3-beta (Is it up to date?)
java.lang.NoSuchMethodError: 'void org.yaml.snakeyaml.nodes.ScalarNode.<init>(org.yaml.snakeyaml.nodes.Tag, java.lang.String, org.yaml.snakeyaml.error.Mark, org.yaml.snakeyaml.error.Mark, org.yaml.snakeyaml.DumperOptions$ScalarStyle)'
	at com.andrei1058.stevesus.libs.configme.resource.yaml.SnakeYamlNodeBuilderImpl.createStringNode(SnakeYamlNodeBuilderImpl.java:96) ~[?:?]
	at com.andrei1058.stevesus.libs.configme.resource.yaml.SnakeYamlNodeBuilderImpl.createYamlNode(SnakeYamlNodeBuilderImpl.java:49) ~[?:?]
	at com.andrei1058.stevesus.libs.configme.resource.YamlFileResource.createAndAddYamlNode(YamlFileResource.java:113) ~[?:?]
	at com.andrei1058.stevesus.libs.configme.resource.YamlFileResource.exportProperties(YamlFileResource.java:71) ~[?:?]
	at com.andrei1058.stevesus.libs.configme.SettingsManagerImpl.save(SettingsManagerImpl.java:80) ~[?:?]
	at com.andrei1058.stevesus.libs.configme.SettingsManagerImpl.loadFromResourceAndValidate(SettingsManagerImpl.java:93) ~[?:?]
	at com.andrei1058.stevesus.libs.configme.SettingsManagerImpl.<init>(SettingsManagerImpl.java:46) ~[?:?]
	at com.andrei1058.stevesus.libs.configme.SettingsManagerBuilder.create(SettingsManagerBuilder.java:141) ~[?:?]
	at com.andrei1058.stevesus.server.ServerManager.<init>(ServerManager.java:58) ~[?:?]
	at com.andrei1058.stevesus.server.ServerManager.onLoad(ServerManager.java:65) ~[?:?]
	at com.andrei1058.stevesus.SteveSus.onLoad(SteveSus.java:82) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:310) ~[patched_1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) ~[patched_1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) ~[patched_1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
[00:26:26] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[00:26:26] [Server thread/INFO]: Preparing level "world"
[00:26:26] [Server thread/INFO]: -------- World Settings For [world] --------
[00:26:26] [Server thread/INFO]: Mob Spawn Range: 4
[00:26:26] [Server thread/INFO]: Cactus Growth Modifier: 100%
[00:26:26] [Server thread/INFO]: Cane Growth Modifier: 100%
[00:26:26] [Server thread/INFO]: Melon Growth Modifier: 100%
[00:26:26] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[00:26:26] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[00:26:26] [Server thread/INFO]: Sapling Growth Modifier: 100%
[00:26:26] [Server thread/INFO]: Wheat Growth Modifier: 100%
[00:26:26] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[00:26:26] [Server thread/INFO]: Vine Growth Modifier: 100%
[00:26:26] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[00:26:26] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[00:26:26] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[00:26:26] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[00:26:26] [Server thread/INFO]: Random Lighting Updates: false
[00:26:26] [Server thread/INFO]: Structure Info Saving: true
[00:26:26] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[00:26:26] [Server thread/INFO]: Max TNT Explosions: 100
[00:26:26] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[00:26:26] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[00:26:26] [Server thread/INFO]: Item Despawn Rate: 6000
[00:26:26] [Server thread/INFO]: Item Merge Radius: 2.5
[00:26:26] [Server thread/INFO]: Arrow Despawn Rate: 1200
[00:26:26] [Server thread/INFO]: View Distance: 10
[00:26:26] [Server thread/INFO]: Experience Merge Radius: 3.0
[00:26:26] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[00:26:26] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[00:26:26] [Server thread/INFO]: Preparing start region for level 0 (Seed: -5719566325902255054)
[00:26:27] [Server thread/INFO]: Preparing spawn area: 98%
[00:26:27] [Server thread/INFO]: [SteveSus] Enabling SteveSus v1.4.3-beta
[00:26:27] [Server thread/ERROR]: Error occurred while enabling SteveSus v1.4.3-beta (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.andrei1058.stevesus.server.ServerManager.getServerType()" because the return value of "com.andrei1058.stevesus.server.ServerManager.getINSTANCE()" is null
	at com.andrei1058.stevesus.server.ServerCommonProvider.<init>(ServerCommonProvider.java:38) ~[?:?]
	at com.andrei1058.stevesus.server.ServerCommonProvider.getInstance(ServerCommonProvider.java:148) ~[?:?]
	at com.andrei1058.stevesus.SteveSus.onEnable(SteveSus.java:122) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[patched_1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) ~[patched_1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) ~[patched_1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) ~[patched_1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) ~[patched_1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) ~[patched_1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) ~[patched_1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) ~[patched_1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) ~[patched_1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
[00:26:27] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[00:26:27] [Server thread/INFO]: Done (1.277s)! For help, type "help" or "?"
```

**Comment by andrei1058** [comment]
It works with
```
        <dependency>
            <groupId>ch.jalu</groupId>
            <artifactId>configme</artifactId>
            <version>1.2.0</version>
        </dependency>
```
